package com.mybatis.demo.entity;

import java.util.Date;

public class Mbg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbg.id
     *
     * @mbg.generated Mon Jul 22 21:05:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbg.name
     *
     * @mbg.generated Mon Jul 22 21:05:46 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mbg.create_time
     *
     * @mbg.generated Mon Jul 22 21:05:46 CST 2019
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbg.id
     *
     * @return the value of mbg.id
     *
     * @mbg.generated Mon Jul 22 21:05:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbg.id
     *
     * @param id the value for mbg.id
     *
     * @mbg.generated Mon Jul 22 21:05:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbg.name
     *
     * @return the value of mbg.name
     *
     * @mbg.generated Mon Jul 22 21:05:46 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbg.name
     *
     * @param name the value for mbg.name
     *
     * @mbg.generated Mon Jul 22 21:05:46 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mbg.create_time
     *
     * @return the value of mbg.create_time
     *
     * @mbg.generated Mon Jul 22 21:05:46 CST 2019
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mbg.create_time
     *
     * @param create_time the value for mbg.create_time
     *
     * @mbg.generated Mon Jul 22 21:05:46 CST 2019
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }
}